### ISSUE TITLE
Cannot use key ID as key_index when using LexikJoseEncoder

### ISSUE THREAD

**Issue by bwowk** [Spomky-Labs/lexik-jose-bridge#33]
the `key_index` setting can be an integer or the key ID (string), but [LexikJoseEncoder 's constructor expects it as an integer](https://github.com/Spomky-Labs/lexik-jose-bridge/blob/2d02f32321a76bd024961f069e7625d0328a56f5/Encoder/LexikJoseEncoder.php#L136), so there's no way to use the key ID.

**Comment by Spomky** [comment]
You are right there is something wrong here.
I will add the possibility the use either an ineger or the key ID.

**Comment by bwowk** [comment]
thanks for the prompt responses 🙂

**Comment by Spomky** [comment]
Done. Tagged as `v2.0.3`.
