### ISSUE TITLE
Allow loading keysets from files

### ISSUE THREAD

**Issue by bwowk** [Spomky-Labs/lexik-jose-bridge#34]
Please add support for loading keysets from files, so it's easier to migrate from 1.x

**Comment by Spomky** [comment]
If you are using Symfony 3.4+, it can be acheived using [the new env var processors](https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables).

Ex. if your key set is stored in `/path/to/signature.jwkset`, then simply use `%env(file:SIGNATURE_KEYSET)%` in the bundle configuration and the env var `SIGNATURE_KEYSET=/path/to/signature.jwkset`.

I will document that in a migration guide.
If you are using Symfony 3.3, I do not see any way to solve that issue at the moment.

**Comment by Spomky** [comment]
Closing as answered.
I will not include that feature for symfony 3.3 as this version is not maintained anymore.
The env var processor available from Symfony 3.4|4.x should be enough.
