### ISSUE TITLE
Flex recipe - generated key_index

### ISSUE THREAD

**Issue by JindrichPilar** [Spomky-Labs/lexik-jose-bridge#44]
While following the installation instructions I encountered a problem with configuration for ``key_index``, for both signature and encryption.

The`` key_index`` and kid in data generated by Flex recipe do not match in .env and in the yaml config.

Which resulted in
> An error occurred while trying to encode the JWT token: Undefined index.
> In LexikJoseEncoder.php (line 193)

After changing ``key_index`` to match kid everything works.

**Comment by Spomky** [comment]
thank you for the issue.
I wiil update https://github.com/symfony/recipes-contrib/blob/master/spomky-labs/lexik-jose-bridge/2.0/manifest.json accordingly

**Comment by Spomky** [comment]
Should be solved now.
Feel free to reopen if not.
