### ISSUE TITLE
Missing dependency for Assert in 3.0.0

### ISSUE THREAD

**Issue by ghost** [Spomky-Labs/lexik-jose-bridge#50]
Seems like it was required indirectly before but isn't anymore

**Comment by Spomky** [comment]
Thanks for this issue.
A patch will be submitted soon on both v3.0 and v2.2 branches

**Comment by otereshchenkov** [comment]
I've created a PR #51 to fix this issue. Basically I removed 2 lines of code with `Assertion` class since, I believe, it was introduced accidentally

**Comment by otereshchenkov** [comment]
Looks like this bug can be closed, right?

**Comment by Djamy** [comment]
Hi @Spomky !

It seems that the tagged version v3.0.0 is still with the [issue](https://github.com/Spomky-Labs/lexik-jose-bridge/blob/v3.0.0/DependencyInjection/Configuration.php#L30).
I think you need to upgrade the version to a newer tag to have @tereschenkov 's fix.

**Comment by Spomky** [comment]
Hi @Djamy,

Thank you for your patience. I’ve just push a fix for that issue.
This should work fine now. Waiting for CI to finish.

**Comment by Djamy** [comment]
Thank you @Spomky it seems to work so far!

I'm just curious here, could you tell me why you choose to import native PHP function [here](https://github.com/Spomky-Labs/lexik-jose-bridge/commit/2984144175e5dd75a11588466da4d342e041e4b9#diff-7cf2e6e09f51fe48ae8415d2c34cab74R16)?
Is there a specific reason or something?

**Comment by Spomky** [comment]
> Thank you @Spomky it seems to work so far!

Great. I close the issue now. Feel free to open it if something went wrong with the last modifications. 

> I'm just curious here, could you tell me why you choose to import native PHP function here?
Is there a specific reason or something?

`\is_string` is a [micro-optimization](https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/). Php-CS-Fixer is able to import all there function and from my POV it looks easier to read.
In addition, when contributors modify the files, they don't have to brother with this optimization.
