### ISSUE TITLE
Invalid definition for service Jose\Bundle\JoseFramework\DataCollector\CheckerCollector: argument 2 of Jose\Bundle\JoseFramework\DataCollect or\CheckerCollector::addHeaderCheckerManager()

### ISSUE THREAD

**Issue by SkonWodrich** [Spomky-Labs/lexik-jose-bridge#54]
i get the following error message, when running "php bin/console lint:container" in the symfony project:

`Invalid definition for service "Jose\Bundle\JoseFramework\DataCollector\CheckerCollector": argument 2 of "Jose\Bundle\JoseFramework\DataCollector\CheckerCollector::addHeaderCheckerManager()" accepts "Jose\Bundle\JoseFramework\Services\HeaderCheckerManager", "Jose\Component\Signature\JWSVerifier" passed.
`
the linter is part of our deployment process and i need to solve the issue to use the bundle

**To Reproduce**
i guess install the package and run the linter "php bin/console lint:container"

symfony 4.4.*, php 7.4.1

**Comment by Spomky** [comment]
Hi @SkonWodrich,

Thank you for your patience. THis should be solved by updating the `jwt-framework` to `v2.2.8`.
Let me konw if you still have this issue with up to date dependencies.

Regqrds.

**Comment by SkonWodrich** [comment]
Hello @Spomky, this solved my issue! thanks a lot. A well deserved star from me. :) cheers jens
