### ISSUE TITLE
Add support of multi-environment configuration.

### ISSUE THREAD

**Issue by burstmeman** [Spomky-Labs/lexik-jose-bridge#58]
As we can see,[ the config is only loaded from the initial config file](https://github.com/Spomky-Labs/lexik-jose-bridge/blob/v3.0/DependencyInjection/SpomkyLabsLexikJoseExtension.php#L78), but it would be nice to add support for multi-environment config.

In my case, I want to use a prod environment remote keyset and a local keyset in a development and test environment.

**Comment by Spomky** [comment]
Hi,

You are right, the configuration should correctly tkae into account the current env conf.

**Comment by Spomky** [comment]
Merged and tagged v3.0.3
