### ISSUE TITLE
Question: Symfony 6 support

### ISSUE THREAD

**Issue by a-menshchikov** [Spomky-Labs/lexik-jose-bridge#61]
@Spomky hello!
Have you any plans about this repo, in particular to add Symfony 6 support in the near future?

**Comment by Spomky** [comment]
Hi @a-menshchikov,

I am sorry I had no time to manage that, but fortunately a PR is opened for that. See #60.

**Comment by a-menshchikov** [comment]
@Spomky 
Thank you for response. I close this issue in favor of the PR. I hope it will be merged soon.
