### ISSUE TITLE
Is it possible to call a service for key_set?

### ISSUE THREAD

**Issue by krakettte** [Spomky-Labs/lexik-jose-bridge#71]
Hello,
Is it possible to define a service which returns the **key_set** instead of of the **%env(LEXIK_JOSE_SIGNATURE_KEYSET)%**?
```
lexik_jose:
    key_set: '%env(LEXIK_JOSE_SIGNATURE_KEYSET)%'
```
Thank

**Comment by Spomky** [comment]
Hi,

The bundle is not designed for that, but that could be a nice feature
